apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowflake-ingress
  annotations:
    kubernetes.io/ingress.class: contour  # указываем какой Ingress Controller использовать
spec:
  rules:
    - host: snowflake.dev.local           # доменное имя из /etc/hosts
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:                      # куда перенаправлять трафик
              service:
                name: snowflake-service   # имя сервиса из app-service.yml
                port:
                  number: 8080            # порт сервиса