apiVersion: v1
kind: ConfigMap
metadata:
  name: snowflake-config
data:
  SPRING_APPLICATION_NAME: "Snowflake ID Generator"
  SNOWFLAKE_SETTINGS_STARTING_EPOCH: "946684800"
  SNOWFLAKE_SETTINGS_DATACENTER_ID: "1"
