apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snowflake-app
  labels:
    app: snowflake-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowflake-app
  template:
    metadata:
      labels:
        app: snowflake-app
    spec:
      initContainers:
        - name: generate-worker-id
          image: busybox:1.36
          command: ["sh", "-c", "echo $(shuf -i 1-31 -n 1) > /config/worker-id"]
          volumeMounts:
            - name: worker-id-volume
              mountPath: /config
      containers:
        - name: snowflake-app
          image: snowflake-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: snowflake-config
                  key: SPRING_APPLICATION_NAME
            - name: SNOWFLAKE_SETTINGS_STARTING_EPOCH
              valueFrom:
                configMapKeyRef:
                  name: snowflake-config
                  key: SNOWFLAKE_SETTINGS_STARTING_EPOCH
            - name: SNOWFLAKE_SETTINGS_DATACENTER_ID
              valueFrom:
                configMapKeyRef:
                  name: snowflake-config
                  key: SNOWFLAKE_SETTINGS_DATACENTER_ID
          command: ["sh", "-c", "export SNOWFLAKE_SETTINGS_WORKED_ID=$(cat /config/worker-id) && java -jar /app/app.jar"]
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: worker-id-volume
              mountPath: /config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
      volumes:
        - name: worker-id-volume
          emptyDir: {}
