apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-app
  labels:
    app: snowflake-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowflake-app
  template:
    metadata:
      labels:
        app: snowflake-app
    spec:
      containers:
        - name: snowflake-app
          image: snowflake-app:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
