spring:
  application:
    name: "Snowflake ID Generator"
  datasource:
    url: jdbc:postgresql://localhost:5432/snowflake_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

snowflake-settings:
  starting-epoch: 946684800
  datacenter-id: 1
  worked-id: 1

management:
  endpoints:
    web:
      base-path: /management
      path-mapping:
        health: health
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
